#!/usr/bin/env bash
set -euo pipefail

: "${LEEWAY_CHATTERBOX_PYTHON:?Set LEEWAY_CHATTERBOX_PYTHON}"
: "${LEEWAY_CHATTERBOX_MODEL_DIR:?Set LEEWAY_CHATTERBOX_MODEL_DIR}"
: "${LEEWAY_CHATTERBOX_REFERENCE:?Set LEEWAY_CHATTERBOX_REFERENCE}"

export LEEWAY_CHATTERBOX_HOST="${LEEWAY_CHATTERBOX_HOST:-127.0.0.1}"
export LEEWAY_CHATTERBOX_PORT="${LEEWAY_CHATTERBOX_PORT:-8792}"
export LEEWAY_CHATTERBOX_THREADS="${LEEWAY_CHATTERBOX_THREADS:-8}"
export LEEWAY_CHATTERBOX_COMPUTE_PROFILE="${LEEWAY_CHATTERBOX_COMPUTE_PROFILE:-CAPACITY_SAFE}"
export LEEWAY_VOICE_ID="${LEEWAY_VOICE_ID:-LEEWAY_VOICE::AGENT_LEE::DEFAULT_CLONE}"
export LEEWAY_SPEAKER_PROFILE_ID="${LEEWAY_SPEAKER_PROFILE_ID:-LEEWAY_SPEAKER::LEONARD_J_LEE::AGENT_LEE}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PROVIDER="$REPO_ROOT/device-runtime/providers/chatterbox-nano-http/server.py"

exec "$LEEWAY_CHATTERBOX_PYTHON" "$PROVIDER"
